version: '3.8'

services:

  db:
    image: postgres:13.4
    container_name: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: devices
    networks:
      - challenge

networks:
  challenge: {}