server:
  port: 8080

spring:
  application:
    name: devices-ms

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

  datasource:
    initialization-mode: always
    platform: postgres
    url: jdbc:postgresql://localhost:5432/devices
    username: admin
    password: admin123